version: '2.3'
services:
  dlf_benchmark_torch_container:
    image: "dlf_benchmark_torch"
    volumes:
      - /home/si/DLF_Benchmark:/workspace:cached
    network_mode: "host"
    shm_size: '8gb'
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: /bin/sh -c "while sleep 1000; do :; done"
