version: '2.3'
services:
  dlf_benchmar_torchk_container:
    image: "dlf_benchmark_torch"
    volumes:
      - /home/si/DLF_Benchmark:/workspace:cached
    network_mode: "host"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

