version: '2.3'
services:
  dlf_benchmark_container:
    image: "dlf_benchmark"
    volumes:
      - /home/si/DLF_Benchmark:/workspace:cached
    network_mode: "host"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    command: /bin/sh -c "while sleep 1000; do :; done"

