version: '2.3'
services:
  dlf_benchmark_tf_container:
    image: "tensorflow/tensorflow"
    volumes:
      - /home/si/DLF_Benchmark:/workspace:cached
    network_mode: "host"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

